apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: development-ff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mini000/fit-factory-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "mysql-service" # MySQL service name for internal communication
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "new_password"
            - name: DB_NAME
              value: "fit_factory"
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
            limits:
              cpu: "1"
              memory: "4Gi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: development-ff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mini000/fit-factory-frontend:latest
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: development-ff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "new_password"
            - name: MYSQL_DATABASE
              value: "fit_factory"
          ports:
            - containerPort: 3306
