apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-resource-quota
  namespace: development
spec:
  hard:
    requests.cpu: "1" # Limit the CPU requests to 1 core
    requests.memory: "2Gi"
    limits.cpu: "1" # Limit the CPU usage to 1 core
    limits.memory: "2Gi"
