apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: production
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000 # Expose port 3000 externally
      targetPort: 3000
  type: LoadBalancer # Exposes the service externally (for cloud environments)
