apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: development
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000 # Expose port 3000
      targetPort: 3000 # Internal backend port
  type: ClusterIP # Service type for internal communication only
