apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: staging-ff
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP



apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  namespace: staging-ff
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-web-service
  namespace: staging-ff
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---

