apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: production-ff
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mini000/fit-factory-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "new_password"
            - name: DB_NAME
              value: "fit_factory"
