apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-quota
  namespace: production-ff
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
